# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-13 07:28
from __future__ import unicode_literals

from django.db import migrations, models
import django_fsm
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0006_auto_20170813_0706'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='state',
            field=django_fsm.FSMField(default='order_placed', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='token',
            field=models.UUIDField(db_index=True, default=uuid.UUID('ff63c67f-e272-471d-b2cf-6fd3dfb81a62')),
        ),
    ]
