# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-13 08:24
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0007_auto_20170813_0728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='token',
            field=models.UUIDField(db_index=True, default=uuid.UUID('335d98fe-3a75-4a77-a8f5-10e6fed3a933')),
        ),
    ]
