# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-22 05:33
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0007_auto_20170813_0728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='items',
        ),
        migrations.AlterField(
            model_name='order',
            name='token',
            field=models.UUIDField(db_index=True, default=uuid.UUID('c3675985-3835-428e-b113-c96e90fdd91a')),
        ),
    ]
