# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-22 05:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0008_auto_20170822_0533'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart_Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='數量')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estore.Cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estore.Product')),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='token',
            field=models.UUIDField(db_index=True, default=uuid.UUID('64756ed8-ecbb-4eb3-a584-f05b5cd55d6a')),
        ),
        migrations.AddField(
            model_name='cart',
            name='items',
            field=models.ManyToManyField(through='estore.Cart_Items', to='estore.Product'),
        ),
    ]
