# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-22 05:59
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0010_auto_20170822_0558'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_items',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='數量'),
        ),
        migrations.AlterField(
            model_name='order',
            name='token',
            field=models.UUIDField(db_index=True, default=uuid.UUID('b41a41b9-ce9c-4d88-983d-708ccc9058a0')),
        ),
    ]
