# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-27 11:06
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0011_auto_20170822_0559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='order',
            name='token',
            field=models.UUIDField(db_index=True, default=uuid.UUID('e0266144-6655-4a59-a4bf-f255ff59427d')),
        ),
    ]
