# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-27 11:08
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0012_auto_20170827_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='數量'),
        ),
        migrations.AlterField(
            model_name='order',
            name='token',
            field=models.UUIDField(db_index=True, default=uuid.UUID('48057e8f-2d13-4aa7-b519-fd86aab9a698')),
        ),
    ]
