# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-27 11:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0013_auto_20170827_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='token',
            field=models.UUIDField(db_index=True, default=uuid.UUID('0f089506-2129-4643-8ec0-223511e71abd')),
        ),
    ]
