# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-28 05:51
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0014_auto_20170827_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='token',
            field=models.UUIDField(db_index=True, default=uuid.UUID('1fb04184-b64e-4ef6-a700-fc99224bf605')),
        ),
    ]
