# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-28 06:56
from __future__ import unicode_literals

from django.db import migrations, models
import spgateway.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0015_auto_20170828_0551'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='SpgatewaySlug',
            field=models.SlugField(default=spgateway.models.generate_slug, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='token',
            field=models.UUIDField(db_index=True, default=uuid.UUID('4745b569-8dab-48e5-975e-2dbcbdbfc314')),
        ),
    ]
