# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-28 07:00
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0016_auto_20170828_0656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='token',
            field=models.UUIDField(db_index=True, default=uuid.UUID('a32257b8-797d-43da-b77d-adccae8d1153')),
        ),
    ]
